server:
#  address: 192.168.3.1
  port: 9001
dubbo:
  application:
    name: crud-service
  registry:
    #注册中心地址
    #制定超时时间,单位毫秒
#    timeout: 5000
    address: zookeeper://192.168.3.1:2181   #单机zookeeper注册中心配置情况
#    address: zookeeper://192.168.2.51:2181?backup=192.168.2.52:2181,192.168.2.53:2181 #zookeeper集群
    #配置元数据中心 --> 用于存储服务的元数据,消费者在消费服务的时候只需要注册中心提供某个服务的关键数据即可,
    #将服务本身必须要但是消费者不需要的数据存放到元数据中心,这样可以提供性能和服务调度的效率
#    simplified: true #注册到注册中心的URL是否采用精简模式的 （与低版本兼容）
#  metadata-report:
#    address: zookeeper://192.168.3.1:2181   #单机zookeeper注册中心配置情况
#    address: zookeeper://192.168.2.51:2181?backup=192.168.2.52:2181,192.168.2.53:2181
  #协议
  protocol:
    name: dubbo
    port: 20888
  #制定扫描的基础包
  scan:
    base-packages: com.example.service.impl
#配置springboot热部署
spring:
  application:
    name: crud-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.1:3306/403forbidden?serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: 123456789
  devtools:
    livereload:
      port: 35730
#    restart:
#      enabled: true
#      #设置重启目录
#      additional-paths: src/main/java
#      exclude: WEB-INF/**
#  freemarker:
#    cache: false  #页面不加载缓存,修改及时生效
  #配置springboot整合solr相关参数(solr-cloud配置如下)
  #  data:
  #    solr:
  #      repositories:
  #        enabled: true  #启用solr仓库
  #      #配置solr-cloud中的zookeeper集群参数
  #      zk-host: 192.168.2.31:2181,192.168.2.32:2181,192.168.2.33:2181
  #配置springboot整合solr相关参数(单机solr配置如下)
#  data:
#    solr:
#      host: http://192.168.2.88:8080/solr/collection1
      #solr-core表示: solr-home目录下的solr目录下的collection1(默认值)目录的名称,
mybatis:
  type-aliases-package: com.example.pojo
  mapper-locations: classpath:mapper/*.xml
